### ISSUE TITLE
"This plugin generated a warning from the characteristic 'Saturation"

### ISSUE THREAD

**Issue by devin987** [cellcortex/homebridge-yeelighter#88] opened 2021-10-20 12:22 UTC
Hello I have since the latest problem that I always have an error message in the log: [homebridge-yeelighter] This plugin generated a warning from the characteristic 'Saturation': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

**Comment by cellcortex** [comment] 2022-04-21 13:56
duplicate of #99

**Closed as completed by cellcortex** 2022-04-21 13:56 UTC
